services:
 api:
  build: .
  ports:
  - "5000:5000"
  volumes:
  - ./src:/app/src
  - ./.env:/app/.env
  - ./serviceAccountKey.json:/app/serviceAccountKey.json
  environment:
  - NODE_ENV=development
  command: npm run dev